name: Dokoiko

# Build Configurations
configs:
  Debug: debug
  Release: release

options:
  bundleIdPrefix: com.tyomashin
  deploymentTarget:
    iOS: 13.0
  developmentLanguage: ja
  # xcodeVersion: "12.3"
  # carthageExecutablePath: mint run Carthage/Carthage carthage

# Build Settings
# ターゲットに依存しない設定
settings:
  # Common
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 4
    DEVELOPMENT_TEAM: 38BV25GUUS
    # SWIFT_VERSION: 5
    # PRODUCT_NAME: $TARGET_NAME
    # Xcode 12.3 で、以下のパラメータが欠落しているとのことなので明示的に指定（デフォルト値）
    # 参考：https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built
    VALIDATE_WORKSPACE: NO
    # 一部のフレームワークでBitCode対応がされていないものがあるためNo指定
    ENABLE_BITCODE: NO
    OTHER_LDFLAGS: -ObjC
    CODE_SIGN_STYLE: Manual
  configs:
    Debug:
      GCC_PREPROCESSOR_DEFINITIONS: DEVELOP=1
      OTHER_SWIFT_FLAGS: -D DEVELOP
      CODE_SIGN_IDENTITY: Apple Development
      PROVISIONING_PROFILE_SPECIFIER: dokoiko_develop
    Release:
      GCC_PREPROCESSOR_DEFINITIONS: "$(inherited)"
      OTHER_SWIFT_FLAGS: "$(inherited)"
      CODE_SIGN_IDENTITY: Apple Development
      PROVISIONING_PROFILE_SPECIFIER: dokoiko_product

targets:
  Dokoiko:
    type: application
    platform: iOS
    sources: 
      - Dokoiko
      - path: Carthage/Build/iOS/GoogleMaps.framework/Resources/GoogleMaps.bundle
        optional: true
        type: folder
      # 自動生成するソースのパスを追加
      # 以下はサンプル
      ## Mockoloで生成するファイル
      # - path: "Foo/Generated/MockResults.swift"
      #   optional: true
      #  type: file
    settings:
      base: 
        INFOPLIST_FILE: Dokoiko/Info.plist
        TARGETED_DEVICE_FAMILY: 1
    preBuildScripts:
      - script: |
                if which mint >/dev/null; then
                  xcrun --sdk macosx mint run swiftymocky generate
                else
                 echo "warning: swiftymocky not installed"
                fi
        name: Run Script (SwiftyMocky)
      - script: |
                if which mint >/dev/null; then
                  xcrun --sdk macosx mint run swiftformat swiftformat . --exclude Carthage,Pods --stripunusedargs closure-only --disable strongOutlets,trailingCommas
                else
                 echo "warning: SwiftFormat not installed"
                fi
        name: Run Script (Swift Format)
    postCompileScripts:
      - script: |
                if which mint >/dev/null; then
                  xcrun --sdk macosx mint run swiftlint swiftlint autocorrect --format
                  xcrun --sdk macosx mint run swiftlint swiftlint
                else
                  echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
                fi
        name: Run Script (SwiftLint)
      - script: |
                if which mint >/dev/null; then
                  xcrun --sdk macosx mint run swiftgen
                else
                  echo "failed SwiftGen Run Script"
                fi
        name: Run Script (SwiftGen)
      - script: |
                if which mint >/dev/null; then
                  xcrun --sdk macosx mint run carthage copy-frameworks
                else
                  echo "failed SwiftGen Run Script"
                fi
        name: Run Script (Copy Framework)
        inputFiles:
          # arcive した後にAppStoreConnectにアップロードしようとした際に、以下のテスト用フレームワークを入れておくとエラーになる
          #- $(SRCROOT)/Carthage/Build/RxBlocking.xcframework/ios-arm64_i386_x86_64-simulator/RxBlocking.framework
          #- $(SRCROOT)/Carthage/Build/RxTest.xcframework/ios-arm64_i386_x86_64-simulator/RxTest.framework
          - $(SRCROOT)/Carthage/Build/iOS/Realm.framework
          - $(SRCROOT)/Carthage/Build/iOS/RealmSwift.framework
        outputFiles:
          #- $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/RxBlocking.framework
          #- $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/RxTest.framework
          - $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Realm.framework
          - $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/RealmSwift.framework
    # 依存するライブラリなどを指定
    dependencies:
      - framework: Carthage/Build/RxSwift.xcframework
      - framework: Carthage/Build/RxCocoa.xcframework
      - framework: Carthage/Build/RxRelay.xcframework
      - framework: Carthage/Build/Alamofire.xcframework
      - framework: Carthage/Build/OHHTTPStubs.xcframework
      # RealmはCarthageでXCFrameworkを作成できないため、frameworkで指定
      #- framework: Carthage/Build/iOS/RealmSwift.framework
      #- framework: Carthage/Build/iOS/Realm.framework
      - framework: Carthage/Build/Lottie.xcframework
      - framework: Carthage/Build/Kingfisher.xcframework
      # GoogleMap導入（参考リンクメモ）
      # https://nekowen.hatenablog.jp/entry/2020/09/01/133812
      # https://stackoverflow.com/questions/8171164/ios-objc-class-cttelephonynetworkinfo-not-found
      # https://developers.google.com/maps/documentation/ios-sdk/v3-client-migration#use-carthage
      - carthage: GoogleMaps
        embed: false
      - carthage: GoogleMapsBase
        embed: false
      - carthage: GoogleMapsCore
        embed: false
      - carthage: Realm
        embed: false
      - carthage: RealmSwift
        embed: false
      - sdk: libc++.tbd
      - sdk: libz.tbd
      - sdk: CoreTelephony.framework
      #- framework: Carthage/Build/RxBlocking.xcframework
      #- framework: Carthage/Build/RxTest.xcframework
      #- framework: Carthage/Build/SwiftyMocky.xcframework
      #- framework: Carthage/Build/SwiftyPrototype.xcframework

  DokoikoTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - DokoikoTests
      # リソースを使用する場合はここにパスを追加する
      # memo: 
      # ターゲット内に一つもリソースが存在しない場合、Build Phases の Copy Bundle Resources セクションが作成されず、
      # swift ファイル以外のリソースの Target Membership にチェックを入れられなくなる。
      # - Dokoiko/Resources
      # - Dokoiko
    settings:
      base: 
        INFOPLIST_FILE: DokoikoTests/Info.plist
    dependencies:
      - target: Dokoiko
      # memo: テスト用のフレームワークをメインターゲットで指定すると実行時にエラーが出るため、テストターゲットで指定している
      # memo: Test Target には XCFramework が使えないため、シミュレータ用のframeworkのみ指定している
      # https://dev.classmethod.jp/articles/build-carthage-use-xcframework/
      - framework: Carthage/Build/RxBlocking.xcframework/ios-arm64_i386_x86_64-simulator/RxBlocking.framework
      - framework: Carthage/Build/RxTest.xcframework/ios-arm64_i386_x86_64-simulator/RxTest.framework 
      - framework: Carthage/Build/SwiftyMocky.xcframework/ios-arm64_i386_x86_64-simulator/SwiftyMocky.framework
      - framework: Carthage/Build/SwiftyPrototype.xcframework/ios-arm64_i386_x86_64-simulator/SwiftyPrototype.framework

  DokoikoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: 
      - DokoikoUITests
      # - Dokoiko
    settings:
      base: 
        INFOPLIST_FILE: DokoikoUITests/Info.plist
    dependencies:
      - target: Dokoiko
      - framework: Carthage/Build/RxBlocking.xcframework/ios-arm64_i386_x86_64-simulator/RxBlocking.framework
      - framework: Carthage/Build/RxTest.xcframework/ios-arm64_i386_x86_64-simulator/RxTest.framework 
      - framework: Carthage/Build/SwiftyMocky.xcframework/ios-arm64_i386_x86_64-simulator/SwiftyMocky.framework
      - framework: Carthage/Build/SwiftyPrototype.xcframework/ios-arm64_i386_x86_64-simulator/SwiftyPrototype.framework


# スキームの設定。一旦参考サイトをコピペで記載している
# https://qiita.com/uhooi/items/16a870eaae24b46103fb
schemes:
  Dokoiko:
    build:
      targets:
        Dokoiko: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Dokoiko
      targets:
        - name: DokoikoTests
          parallelizable: true
          randomExecutionOrder: true
        - name: DokoikoUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
